### ISSUE TITLE
Monster health progress bar CSS suggestions

### ISSUE THREAD

**Issue by joetweber** [ninjawithkillmoon/gloomhaven-companion#41]
Hi all,

First of all, my GH group _loves_ this project—**awesome work**. I'm sure (I hope) you hear this all the time, but can you ever really hear it enough? 😉

I have a suggestion for some improved CSS styling of the health progress bars in the monsterHealth utility. This would beef up the progress bars so they're the same size as the buttons, and enhance the size and legibility of the HP numbers (but not too much, so they still fit nicely when the value is 1).

See the example screenshot below, followed by the edits to the code.

![screen shot 2018-01-08](https://user-images.githubusercontent.com/35237437/34690149-9a1be892-f47d-11e7-9a12-f80e44ecb4b2.jpg)

```css
.monster-heath-monsters-container .progress {
    margin-top: 0px;  /* was 7px */
}

.progress {
    height: 44px;  /* was 20px */
}

.progress-bar {
    font-size: 18px;  /* was 12px */
    line-height: 40px;  /* was 20px */
    font-weight: bold;  /* added this */
}
```

Since the progress bars are (arguably) the most important part of the utility, I thought these tweaks would be helpful. Just the 2¢ of a visual design guy; take it or leave it. 😄
